FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r requirements.txt

COPY app ${LAMBDA_TASK_ROOT}/app
COPY scheduled_handler.py scraper_handlers.py ${LAMBDA_TASK_ROOT}/

CMD ["scraper_handlers.default_handler"]
